version: '3.9'
services:
  app:
    build: .
    container_name: disys
    depends_on:
      - database
    ports:
      - 8080:8080
  database:
    image: "postgres"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=disys

   